#!/usr/bin/env python3
"""
run_presidential_irv_2028.py
-----------------------------
Alternative scenario: IRV (Instant Runoff Voting) for the 5-person
presidential general election, using the same finalists from the
Ranked Pairs primary.

Reads existing presidential_ballots.csv (already generated by
generate_presidential_ballots.py) — no re-simulation needed.

Finalists (from Ranked Pairs primary):
  CON_SD, SD_CON, SD_STY, CON_STY, REF_STY

Outputs (Claude/outputs/irv/):
  irv_presidential_national_2028.csv  — round-by-round national IRV
  irv_presidential_states_2028.csv    — winner + runner-up per state
"""

import numpy as np
import pandas as pd
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────
BASE_DIR        = Path(__file__).parent.parent
TYPOLOGY_PATH   = BASE_DIR / "data" / "processed" / "typology_cluster_assignments.csv"
BALLOTS_PATH    = BASE_DIR / "data" / "outputs" / "presidential_ballots.csv"
PRIMARY_PATH    = BASE_DIR / "data" / "outputs" / "primary_results_2028.csv"
OUTPUT_DIR      = BASE_DIR / "data" / "outputs" / "irv"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Finalists: loaded dynamically from primary_results_2028.csv in main() ──
# These module-level globals are overwritten at runtime; do not edit manually.
FINALISTS:       list[str]       = []
FINALIST_LABELS: dict[str, str]  = {}

FIPS_TO_ABBR = {
     1:"AL",  2:"AK",  4:"AZ",  5:"AR",  6:"CA",  8:"CO",  9:"CT",
    10:"DE", 11:"DC", 12:"FL", 13:"GA", 15:"HI", 16:"ID", 17:"IL",
    18:"IN", 19:"IA", 20:"KS", 21:"KY", 22:"LA", 23:"ME", 24:"MD",
    25:"MA", 26:"MI", 27:"MN", 28:"MS", 29:"MO", 30:"MT", 31:"NE",
    32:"NV", 33:"NH", 34:"NJ", 35:"NM", 36:"NY", 37:"NC", 38:"ND",
    39:"OH", 40:"OK", 41:"OR", 42:"PA", 44:"RI", 45:"SC", 46:"SD",
    47:"TN", 48:"TX", 49:"UT", 50:"VT", 51:"VA", 53:"WA", 54:"WV",
    55:"WI", 56:"WY", 72:"PR",
}


# ═══════════════════════════════════════════════════════════════════════════
# IRV helpers
# ═══════════════════════════════════════════════════════════════════════════

def extract_finalist_ballots(ballots_df: pd.DataFrame) -> np.ndarray:
    """
    From full 17-candidate ballots, extract restricted ballots containing
    only the 5 finalists in their original preference order.

    Returns (N, 5) object array — each row is a ranked list of finalist codes.
    """
    finalist_set = set(FINALISTS)
    rank_cols = [c for c in ballots_df.columns if c.startswith("rank_")]
    raw = ballots_df[rank_cols].values  # (N, 17)

    N = len(raw)
    F = len(FINALISTS)
    out = np.empty((N, F), dtype=object)

    for i in range(N):
        row = raw[i]
        filtered = [code for code in row if code in finalist_set]
        out[i] = filtered  # always exactly 5 (all finalists appear in every ballot)

    return out


def first_surviving_choice(ballots: np.ndarray, active: set) -> np.ndarray:
    """Return each ballot's first choice among active candidates."""
    N = len(ballots)
    result = np.full(N, "__exhausted__", dtype=object)
    for i in range(N):
        for code in ballots[i]:
            if code in active:
                result[i] = code
                break
    return result


def run_irv(ballots: np.ndarray, weights: np.ndarray,
            candidates: list[str]) -> list[dict]:
    """
    Run IRV to completion.  Returns list of round dicts with:
      round, eliminated, vote_totals (dict code→pct), active_set
    Tiebreak: alphabetical (eliminate lowest code first).
    Runner-up = last eliminated before winner.
    """
    active = set(candidates)
    rounds = []
    total_w = float(weights.sum())

    while len(active) > 1:
        fsc = first_surviving_choice(ballots, active)
        totals = {}
        for code in active:
            mask = fsc == code
            totals[code] = float(weights[mask].sum())

        # Check majority
        winner_candidates = [c for c, v in totals.items() if v > total_w / 2]

        # Build round record
        round_record = {
            "round":     len(rounds) + 1,
            "active":    sorted(active),
            "totals":    {c: round(totals[c], 4) for c in sorted(active)},
            "pcts":      {c: round(totals[c] / total_w * 100, 4) for c in sorted(active)},
            "eliminated": None,
        }

        if winner_candidates:
            round_record["eliminated"] = None
            rounds.append(round_record)
            break

        # Eliminate lowest (alphabetical tiebreak)
        loser = min(active, key=lambda c: (totals[c], c))
        round_record["eliminated"] = loser
        rounds.append(round_record)
        active.discard(loser)

    return rounds


def summarise_irv(rounds: list[dict], candidates: list[str]) -> dict:
    """Extract winner and runner-up from completed IRV rounds."""
    elimination_order = [r["eliminated"] for r in rounds if r["eliminated"]]
    remaining = [c for c in candidates if c not in elimination_order]
    last_pcts = rounds[-1]["pcts"] if rounds else {}
    winner    = max(remaining, key=lambda c: last_pcts.get(c, 0)) if remaining else "none"
    runner_up = elimination_order[-1] if elimination_order else "none"
    return {"winner": winner, "runner_up": runner_up,
            "winner_label":    FINALIST_LABELS.get(winner, winner),
            "runner_up_label": FINALIST_LABELS.get(runner_up, runner_up)}


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

def main():
    global FINALISTS, FINALIST_LABELS

    # ── Load finalists from primary output (never hardcoded) ──────────────
    print(f"Loading finalists from {PRIMARY_PATH.name}…")
    primary_df = pd.read_csv(PRIMARY_PATH)
    finalist_rows = primary_df[
        (primary_df["winnowing_point"] == "After_Pod_BD") &
        (primary_df["status"] == "surviving")
    ][["candidate_code", "candidate_name"]].drop_duplicates()
    FINALISTS       = sorted(finalist_rows["candidate_code"].tolist())
    FINALIST_LABELS = dict(zip(finalist_rows["candidate_code"], finalist_rows["candidate_name"]))
    print(f"  Finalists ({len(FINALISTS)}): {', '.join(FINALIST_LABELS[c] for c in FINALISTS)}")

    print("Loading data…")
    typology = pd.read_csv(TYPOLOGY_PATH)
    ballots_df = pd.read_csv(BALLOTS_PATH)

    print(f"  Respondents: {len(typology):,}")
    print(f"  Ballot rows: {len(ballots_df):,}")

    weights     = typology["commonpostweight"].values
    state_fips  = typology["inputstate"].values.astype(int)

    # Build restricted finalist ballots
    print("Extracting finalist sub-ballots…")
    ballots = extract_finalist_ballots(ballots_df)  # (N, 5)
    print(f"  Ballot shape: {ballots.shape}")

    # ── National IRV ──────────────────────────────────────────────────────
    print("\nRunning national IRV…")
    nat_rounds = run_irv(ballots, weights, FINALISTS)
    nat_result = summarise_irv(nat_rounds, FINALISTS)

    print(f"\n{'='*60}")
    print(f"NATIONAL IRV RESULT")
    print(f"{'='*60}")
    for rnd in nat_rounds:
        pcts = "  ".join(f"{FINALIST_LABELS[c]}={rnd['pcts'][c]:.1f}%" for c in rnd["active"])
        elim = f"  → ELIMINATE {FINALIST_LABELS.get(rnd['eliminated'], '')}"\
               if rnd["eliminated"] else "  → WINNER DETERMINED"
        print(f"  Round {rnd['round']:1d}: {pcts}{elim}")
    print(f"\n  Winner:    {nat_result['winner_label']} ({nat_result['winner']})")
    print(f"  Runner-up: {nat_result['runner_up_label']} ({nat_result['runner_up']})")

    # Save national round-by-round
    nat_rows = []
    for rnd in nat_rounds:
        for code in FINALISTS:
            if code in rnd["totals"]:
                nat_rows.append({
                    "round":         rnd["round"],
                    "candidate_code": code,
                    "candidate_name": FINALIST_LABELS[code],
                    "vote_total":    rnd["totals"][code],
                    "vote_pct":      rnd["pcts"][code],
                    "eliminated":    (rnd["eliminated"] == code),
                    "winner":        (nat_result["winner"] == code),
                })
    nat_df = pd.DataFrame(nat_rows)
    nat_path = OUTPUT_DIR / "irv_presidential_national_2028.csv"
    nat_df.to_csv(nat_path, index=False)
    print(f"\nSaved national rounds → {nat_path}")

    # ── Per-state IRV ─────────────────────────────────────────────────────
    print("\nRunning per-state IRV…")
    unique_states = sorted(set(state_fips))
    state_rows = []

    for fips in unique_states:
        mask = state_fips == fips
        if mask.sum() < 5:
            continue
        s_ballots = ballots[mask]
        s_weights = weights[mask]
        abbr = FIPS_TO_ABBR.get(fips, f"FIPS{fips}")

        s_rounds = run_irv(s_ballots, s_weights, FINALISTS)
        s_result = summarise_irv(s_rounds, FINALISTS)

        # First-choice shares in round 1
        r1 = s_rounds[0]["pcts"] if s_rounds else {}
        row = {
            "state_fips":        fips,
            "state_abbr":        abbr,
            "winner_code":       s_result["winner"],
            "winner_label":      s_result["winner_label"],
            "runner_up_code":    s_result["runner_up"],
            "runner_up_label":   s_result["runner_up_label"],
            "n_respondents":     int(mask.sum()),
            "n_irv_rounds":      len(s_rounds),
        }
        # Add first-choice pcts for each finalist
        for code in FINALISTS:
            lbl = FINALIST_LABELS[code].replace("/", "_")
            row[f"r1_pct_{lbl}"] = round(r1.get(code, 0.0), 2)
        state_rows.append(row)

    state_df = pd.DataFrame(state_rows)
    state_path = OUTPUT_DIR / "irv_presidential_states_2028.csv"
    state_df.to_csv(state_path, index=False)
    print(f"Saved state results → {state_path}  ({len(state_df)} states)")

    # ── Console summary ───────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print("STATE RESULTS (IRV — winner / runner-up)")
    print(f"{'='*60}")
    win_counts = state_df["winner_label"].value_counts()
    print("\nStates won:")
    for lbl, cnt in win_counts.items():
        print(f"  {lbl:<10} {cnt:2d}")

    print(f"\n{'Abbr':<6} {'Winner':<10} {'Runner-up':<10} {'Rds':>3}  First-choice %")
    print("-" * 65)
    for _, row in state_df.sort_values("state_abbr").iterrows():
        def r1_pct(c):
            col = f"r1_pct_{FINALIST_LABELS[c].replace('/', '_')}"
            return f"{FINALIST_LABELS[c]}={row[col]:.0f}%"
        r1_strs = " ".join(r1_pct(c) for c in FINALISTS)
        print(f"  {row['state_abbr']:<4} {row['winner_label']:<10} {row['runner_up_label']:<10}"
              f" {int(row['n_irv_rounds']):>2}   {r1_strs}")

    print("\n✓ Presidential IRV complete.")


if __name__ == "__main__":
    main()
